### ISSUE TITLE
Update to team 2023

### ISSUE THREAD

**Issue by tedxace** [rajvaya/TEDxACE#5]
Convert team to 2023

**Comment by tedxace** [comment]
@SuhaniBh @Om-Vilas-Kulkarni have a look at the code on how the teams will be updated

**Comment by tedxace** [comment]
@Om-Vilas-Kulkarni once we get all the social media links please update them and put in a pull request. If you have any doubts reach out to the group.

Put your PR to `team-2023` not to `master`.

**Comment by anjannair** [comment]
Thanks @Om-Vilas-Kulkarni issue has been fixed!
